$accent = rgba(ffdeabff) 
$primary = rgba(ffdeabff)
$secondary = rgba(f8dfbbff)
$success = rgba(d0eabfff)
$background = rgba(17130bff)
$surface = rgba(17130bff)
$surface-variant = rgba(4e4539ff)
$on-primary = rgba(422c00ff)
$on-secondary = rgba(3c2e16ff)
$on-surface = rgba(ece1d4ff)
$on-surface-variant = rgba(d2c5b4ff)
$outline = rgba(9b8f80ff)
$outline-variant = rgba(4e4539ff)